---III. Ngôn ngữ truy vấn dữ liệu cấu trúc:
--Câu 1
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'TRUNG QUOC'

--Câu 2
SELECT MASP, TENSP
FROM SANPHAM
WHERE DVT IN('CAY', 'QUYEN')

--Câu 3
SELECT MASP, TENSP
FROM SANPHAM
WHERE MASP LIKE'B%01'

--Câu 4
SELECT MASP,TENSP,NUOCSX
FROM SANPHAM
WHERE NUOCSX = 'TRUNG QUOC'
AND GIA BETWEEN 30000 AND 40000

--Câu 5
SELECT MASP, TENSP, NUOCSX
FROM SANPHAM
WHERE (NUOCSX = 'TRUNG QUOC' OR NUOCSX = 'THAI LAN') AND GIA BETWEEN 30000 AND 40000

--Câu 6
SELECT SOHD, TRIGIA
FROM HOADON
WHERE NGHD >= '1/1/2007' AND NGHD <= '1/2/2007'

--Câu 7
SELECT SOHD, TRIGIA
FROM HOADON
WHERE MONTH(NGHD) = 1 AND YEAR(NGHD) = 2007
ORDER BY NGHD ASC, TRIGIA DESC

--Câu 8
SELECT K.MAKH, HOTEN
FROM KHACHHANG K INNER JOIN HOADON H
ON K.MAKH = H.MAKH
WHERE NGHD = '1/1/2007'

--Câu 9
SELECT SOHD, TRIGIA
FROM HOADON H INNER JOIN NHANVIEN N
ON H.MANV = N.MANV
WHERE NGHD = '10/28/2006'
AND HOTEN = 'NGUYEN VAN B'

--Câu 10
SELECT DISTINCT S.MASP, TENSP
FROM SANPHAM S INNER JOIN CTHD C
ON S.MASP = C.MASP
AND EXISTS(SELECT *
FROM CTHD C INNER JOIN HOADON H
ON C.SOHD = H.SOHD
AND MONTH(NGHD) = 10 AND YEAR(NGHD) = 2006 AND MAKH IN(SELECT H.MAKH
FROM HOADON H INNER JOIN KHACHHANG K
ON H.MAKH = K.MAKH
WHERE HOTEN = 'NGUYEN VAN A') AND S.MASP = C.MASP)

--Câu 11
SELECT DISTINCT SOHD 
FROM CTHD
WHERE MASP ='BB01' OR MASP = 'BB02'

--Câu 12
SELECT DISTINCT SOHD 
FROM CTHD
WHERE ( MASP ='BB01' OR MASP = 'BB02' ) AND SL BETWEEN 10 AND 20

--Câu 13
SELECT SOHD
FROM CTHD A
WHERE MASP = 'BB01' AND A.SL BETWEEN 10 AND 20 AND EXISTS 
  (
	SELECT SOHD 
	FROM CTHD B
	WHERE MASP = 'BB02' AND A.SOHD = B.SOHD AND B.SL BETWEEN 10 AND 20
	)

--Câu 14
SELECT MASP , TENSP
FROM SANPHAM 
WHERE NUOCSX ='Trung Quoc'
UNION
SELECT SANPHAM.MASP , TENSP
FROM (HOADON JOIN CTHD ON HOADON.SOHD = CTHD.SOHD ) JOIN SANPHAM ON SANPHAM.MASP = CTHD.MASP
WHERE NGHD = '1/1/2007'

--Câu 15
SELECT SANPHAM.MASP , TENSP
FROM SANPHAM 
WHERE NOT EXISTS 
	(
	SELECT MASP
	FROM CTHD 
	WHERE SANPHAM.MASP = CTHD.MASP
	)