--Câu 16
SELECT MASP, TENSP
FROM  SANPHAM
WHERE MASP NOT IN ( SELECT A.MASP
     FROM  CTHD A, HOADON B
     WHERE A.SOHD=B.SOHD AND YEAR(NGHD)=2006)
--Câu 17
SELECT MASP, TENSP
FROM  SANPHAM
WHERE NUOCSX=N'Trung Quoc' and MASP NOT IN ( SELECT A.MASP
     FROM  CTHD A, HOADON B
     WHERE A.SOHD=B.SOHD AND YEAR(NGHD)=2006)
--Câu 18
SELECT DISTINCT SOHD
FROM  CTHD A
WHERE EXISTS(SELECT *
    FROM  SANPHAM B
    WHERE NUOCSX='SINGAPORE' AND
       EXISTS(SELECT *
        FROM  CTHD C
        WHERE C.MASP=B.MASP AND C.SOHD=A.SOHD))
--Câu 19
--Câu 20
SELECT COUNT(SOHD)
FROM  HOADON
WHERE MAKH IS NULL
--Câu 21
SELECT COUNT(DISTINCT MASP)
FROM  HOADON A, CTHD B
WHERE A.SOHD=B.SOHD AND YEAR(NGHD)=2006
--Câu 22
SELECT MAX(TRIGIA) [TRI GIA CAO NHAT],MIN(TRIGIA) [TRI GIA THAP NHAT] 
FROM  HOADON
--Câu 23
SELECT AVG(TRIGIA)
FROM  HOADON
WHERE YEAR(NGHD)=2006
--Câu 24
SELECT SUM(TRIGIA) [DOANH THU]
FROM  HOADON
WHERE YEAR(NGHD)=2006
--Câu 25
SELECT SOHD
FROM HOADON
WHERE TRIGIA= (SELECT MAX(TRIGIA) FROM HOADON WHERE YEAR(NGHD) = '2006' )
--Câu 26
SELECT HOTEN
FROM KHACHHANG
inner join HOADON on HOADON.MAKH = KHACHHANG.MAKH
WHERE TRIGIA = (SELECT MAX(TRIGIA) FROM HOADON WHERE YEAR (NGHD)=2006)
--Câu 27
SELECT MAKH,HOTEN
FROM  KHACHHANG
WHERE DOANHSO IN(SELECT TOP 3 DOANHSO
    FROM   KHACHHANG
    ORDER BY   DOANHSO DESC)  
--Câu 28
SELECT *
FROM  SANPHAM
WHERE GIA IN(SELECT TOP 3  GIA
    FROM   SANPHAM
    ORDER BY   GIA DESC)  
--Câu 29
SELECT *
FROM  SANPHAM
WHERE NUOCSX='THAI LAN' AND GIA IN(SELECT TOP 3  GIA
        FROM   SANPHAM
        ORDER BY   GIA DESC) 
--Câu 30
SELECT *
FROM  SANPHAM
WHERE NUOCSX='TRUNG QUOC' AND GIA IN(SELECT TOP 3  GIA
        FROM   SANPHAM
        WHERE  NUOCSX='TRUNG QUOC'
        ORDER BY   GIA DESC) 
--Câu 31
SELECT *
FROM  KHACHHANG
WHERE DOANHSO IN(SELECT TOP 3 DOANHSO
    FROM   KHACHHANG
    ORDER BY   DOANHSO DESC)  
ORDER BY DOANHSO DESC
--Câu 32
SELECT COUNT(MASP)
FROM  SANPHAM
WHERE NUOCSX='TRUNG QUOC'
--Câu 33
SELECT NUOCSX,COUNT(MASP) [SO SAN PHAM]
FROM  SANPHAM
GROUP BY  NUOCSX
--Câu 34
SELECT NUOCSX,MIN(GIA) [GIA THAP NHAT], AVG(GIA) [GIA TB], MAX(GIA) [GIA CAO NHAT]
FROM  SANPHAM
GROUP BY  NUOCSX
--Câu 35
SELECT NGHD,SUM(TRIGIA) [DOANH THU]
FROM  HOADON
GROUP BY  NGHD