-- III
--Bài 3.16
SELECT MASP , TENSP
FROM SANPHAM 
WHERE NOT EXISTS (
	SELECT MASP
	FROM CTHD 
	INNER JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
	WHERE SANPHAM.MASP = CTHD.MASP AND YEAR(HOADON.NGHD) = 2006
	)
--Bài 3.17
select masp,tensp
from SANPHAM
where NUOCSX='Trung Quoc' and not exists (
		select MASP
		FROM CTHD 
		inner join HOADON on CTHD.SOHD = HOADON.SOHD
		WHERE SANPHAM.MASP = CTHD.MASP AND YEAR(HOADON.NGHD) = '2006'
	)
--Bài 3.18
select SOHD
from HOADON
where not exists (
			select masp
			from sanpham
			where nuocsx='Singapore' and not exists (
				select SOHD
				from CTHD 
				where HOADON.sohd=CTHD.sohd and CTHD.masp=SANPHAM.masp) )
--Bài 3.19
SELECT HOADON.SOHD ,SOLAN
FROM HOADON  JOIN (
			SELECT MIN(SL) SOLAN 
			FROM HOADON HD JOIN (
						SELECT HOADON.SOHD , COUNT(*) SL
						FROM (CTHD JOIN HOADON ON CTHD.SOHD = HOADON.SOHD ) JOIN SANPHAM ON SANPHAM.MASP =CTHD.MASP 
						WHERE NUOCSX = 'Singapore' AND YEAR(NGHD) = 2006 
						GROUP BY HOADON.SOHD) TABLE1 
							ON TABLE1.SOHD = HD.SOHD 
					) TABLE2 ON HOADON.SOHD = TABLE2.SOLAN

SELECT  COUNT (*) AS SOLANMUA 
FROM (CTHD JOIN HOADON ON CTHD.SOHD = HOADON.SOHD ) JOIN SANPHAM ON SANPHAM.MASP = CTHD.MASP
WHERE NUOCSX = 'Singapore'  AND YEAR(NGHD) = 2006
--Bài 3.20
SELECT COUNT(*) AS N'Số hóa đơn không phải do thành viên mua'
FROM HOADON
WHERE MAKH IS NULL
--Bài 3.21
SELECT COUNT(DISTINCT MASP) as N'Sản phẩm khác nhau được bán ra năm 2003'
FROM HOADON 
INNER JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
WHERE YEAR(NGHD) = '2006'
--Bài 3.22
SELECT MIN(TRIGIA) AS N'Hóa đơn Thấp Nhất' , MAX (TRIGIA) AS N'Hóa đơn Cao Nhất'
FROM HOADON
--Bài 3.23
SELECT AVG(TRIGIA) AS N'Trị giá trung bình của tất cả các hóa đơn được bán ra trong năm 2006'
FROM HOADON
WHERE YEAR(NGHD) ='2006'
--Bài 3.24
SELECT SUM(TRIGIA) AS N'Doanh Thu'
FROM HOADON
WHERE YEAR(NGHD) = '2006'
--Bài 3.25
SELECT SOHD
FROM HOADON
WHERE TRIGIA= (SELECT MAX(TRIGIA) FROM HOADON WHERE YEAR(NGHD) = '2006' )
--Bài 3.26
SELECT HOTEN
FROM KHACHHANG
inner join HOADON on HOADON.MAKH = KHACHHANG.MAKH
WHERE TRIGIA = (SELECT MAX(TRIGIA) FROM HOADON WHERE YEAR (NGHD)=2006)
--Bài 3.27
select TOP 3 MAKH, HOTEN
FROM KHACHHANG
ORDER BY DOANHSO DESC
--Bài 3.28
select masp,tensp
from sanpham
where gia in (
	SELECT TOP 3 GIA
	FROM SANPHAM
	ORDER BY GIA DESC
	)
--Bài 3.29
SELECT MASP ,TENSP
FROM SANPHAM
WHERE nuocsx = 'Thai Lan' and GIA IN (
	SELECT TOP 3 GIA
	FROM SANPHAM
	ORDER BY GIA DESC)
--Bài 3.30
SELECT MASP ,TENSP
FROM SANPHAM
WHERE nuocsx = 'Trung Quoc' and GIA IN (
	SELECT TOP 3 GIA
	FROM SANPHAM
	Where nuocsx = 'Trung Quoc'
	ORDER BY GIA DESC)
--Bài 3.31
select *
from khachhang
where DOANHSO in (
	select top 3 DOANHSO
	FROM KHACHHANG
	ORDER BY DOANHSO DESC)
--Bài 3.32
SELECT COUNT (*) AS N'Tổng SOSP'
FROM SANPHAM
WHERE NUOCSX='Trung Quoc'
--Bài 3.33
SELECT NUOCSX , COUNT (*) AS SOSP
FROM SANPHAM
GROUP BY NUOCSX 
--Bài 3.34 
SELECT NUOCSX , MAX(GIA) AS N'Giá cao nhất' , MIN(GIA) AS N'Giá thấp nhất' , AVG(GIA) AS N'Giá Trung Bình'
FROM SANPHAM
GROUP BY NUOCSX
--Bài 3.35
SELECT NGHD , SUM(TRIGIA) AS DOANHTHU
FROM HOADON
GROUP BY NGHD
